# Generated by Django 3.1.5 on 2021-02-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
