# Generated by Django 3.1.5 on 2021-03-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeAutomation_app', '0002_auto_20210307_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
